// Estado mutable compartido. Firebase y la UI siguen siendo las fuentes de estado
// de la partida; este objeto solamente conserva el estado local del cliente.
export const state = {
  mode:null, gameType:null, roomCode:'', playerId:'', playerName:'', hostName:'',
  categories:[], totalRounds:3, roomRef:null, roomListener:null, serverTimeOffset:0,
  myAssignment:null, countdownTimer:null, countdownWatchdogTimer:null, countdownKey:'', countdownPhase:'', countdownEndAt:0, countdownPerformanceEndAt:0, countdownTransitioningKey:'', transitionKey:'', configEditing:false,
  wakeLock:null, countdownFeedbackKey:'', soundUnlocked:false,
  busy:{create:false,join:false,start:false,score:false,confirm:false,next:false,restart:false,reconnect:false,finishGame:false,leave:false},
  restoring:false,autoRestoring:false,authReady:false,authUser:null,anonymousSignInStarted:false,registeringAccount:false,authEventToken:0,profile:null,accountListenerUid:'',lastRoomData:null,currentScreen:'',screenHistory:[],scoringRenderKey:'',privateAssignment:null,privateAssignmentRef:null,privateAssignmentListener:null,miniPrivateAssignmentRef:null,miniPrivateAssignmentListener:null,miniPrivateAssignment:null,tribunalPrivateAssignment:null,tribunalRevealRef:null,tribunalRevealListener:null,tribunalRevealToken:'',tribunalRevealData:null,tribunalRevealPublishedToken:'',tribunalRevealPublishInFlight:false,tribunalRevealFinalizeInFlight:false,chamuyayaPrivateAssignment:null,friendData:{},friendProfiles:{},friendPresence:{},requestData:{},inviteData:{},friendPresenceRefs:{},friendProfileRefs:{},profileListener:null,friendListener:null,requestListener:null,inviteListener:null,accountPresenceRef:null,presenceOnline:false,searchTarget:null,pendingInviteRoom:'',lastConnected:null,connectionWatchdog:null,reconnectModalOpen:false,roomConnectionPaused:false,reconnectTimer:null,reconnectAttempt:0,reconnectStartedAt:0,reconnecting:false,reconnectLastReason:'',globalJoinInFlight:false,privateAssignmentRecoveryTimer:null,privateAssignmentRecoveryAttempts:0,requestListenerInitialized:false,inviteListenerInitialized:false,lastRequestKeys:new Set(),lastInviteKeys:new Set(),guestMode:false,quickFriendsOpen:false,friendsLoaded:false,splashDone:false,hostTransferAttemptKey:'',hostMetadataRepairInFlight:false,pendingRoundToken:'',pendingAssignments:null,assignmentRetryToken:'',assignmentRetryCount:0,assignmentRetryAt:0,roundWriteInProgress:false,assignmentRecoveryInProgress:false,transitionRetryTimer:null,roomHeartbeatTimer:null,roomDirectorySyncKey:'',miniCountdownTimer:null,miniCountdownWatchdog:null,miniCountdownKey:'',miniCountdownTick:null,miniCountdownTransitioningKey:'',miniRenderKey:'',stopFormToken:'',miniConfig:null,whoamiLocal:null,ageLocal:null,ageLocalEstimate:'',ageEstimateRoundToken:'',ageSubmitInFlight:false,confessionsLocal:null,confessionSubmitInFlight:false,confessionVoteInFlight:false,stopDrafts:{},stopDraftTimer:null,chupistica:null,chupisticaTimers:[],stopConfig:null,chamuyayaLocal:null,whatWouldYouDoConfig:null,whatWouldYouDoVoteInFlight:false,tribunalRevealDeadlineTimer:null,tribunalRevealDeadlineKey:''
};
